[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
serde.workspace = true
actix-web.workspace = true
chrono = "0.4.42"
futures-util = "0.3.31"
anyhow = "1.0.100"
